id: P124056D8
initial_creation_type: input
source_metadata:
  title: Bodhicaryāvatāra Series
  language: en
  description: 'Lotsawa House presents the following texts as part of its Bodhicaryāvatāra
    Series:'
  volume:
    4d55cc8fc90240089f632ced908a80a8:
      title: 'Bodhicaryāvatāra—Chapter 1: The Benefits of Bodhicitta'
      parent: Bodhicaryāvatāra Root text
    532ba12cf93d4c1981e167828d3995ec:
      title: 'Bodhicaryāvatāra—Chapter 2: Confession of Negativity'
      parent: Bodhicaryāvatāra Root text
    5184625d07de4b548006f0e3d5e80f9a:
      title: 'Bodhicaryāvatāra—Chapter 3: Fully Adopting Bodhicitta'
      parent: Bodhicaryāvatāra Root text
    657e78f855e14c5fb5a2efe8f20e410a:
      title: 'Bodhicaryāvatāra: Teachings and Overview'
      parent: Commentaries
    c115ed7766364ca481f2c2485a0da3ac:
      title: Overview of the Bodhicaryāvatāra
      parent: Commentaries
    e5a6438ba7494a25be91b8484fdfbed2:
      title: 'The Brightly Shining Sun: A Step-by-Step Guide to Meditating on the
        Bodhicaryāvatāra'
      parent: Commentaries
    3a097fb9ee4c41c0a4b32da8843a183e:
      title: 'The Garland of Jewel Ornaments: The Stages of Meditating on the Bodhicaryāvatāra'
      parent: Commentaries
    0593f1bf2c154d43810402bf6627a0fc:
      title: Bodhicaryāvatāra Lineage Prayer
      parent: Lineage Prayers
    fec9f7ee5eea457097ddb8b13d9665e4:
      title: Prayer to the Lineage of the Bodhicaryāvatāra
      parent: Lineage Prayers
    5756d65f38a142b896fca4a0701813ae:
      title: 'Vines of Amṛta: A Prayer to the Lineage of the Bodhicaryāvatāra'
      parent: Lineage Prayers
created_at: '2022-03-01T03:02:08.554712'
last_modified_at: '2022-03-01T03:02:08.554719'
